### ISSUE TITLE
Bug: error parsing email objects

### ISSUE THREAD

**Issue by b3yond** [b3yond/ticketfrei#40]
# Expected Behavior

when an email is received, it searches for patterns in the body to check if it is appropriate.

# Actual Behavior

it crashes, because the email body is not passed correctly - report.text needs to be a string.

# Traceback:

```
Traceback (most recent call last):
  File "backend.py", line 36, in <module>
    if not user.is_appropriate(status):
  File "/srv/ticketfrei/user.py", line 65, in is_appropriate
    if pattern in report.text.lower():
AttributeError: 'list' object has no attribute 'lower'
```

**Comment by d24phant** [comment]
report.text is fed by the email.message.get_payload() function:

>  The payload is either a string or bytes object, in the case of simple message objects, or a list of EmailMessage objects, for MIME container documents such as multipart/* and message/rfc822 message objects.
(source: https://docs.python.org/3/library/email.message.html )

The case of a simple string or bytes object is well covered, the problem here is that it was the only test case ;)

We need to decide how we treat the EmailMessage objects in this list; do we want to put all of them in report.text?

**Comment by b3yond** [comment]
untreated MIMEtypes which are multipart are logged - we should revisit this once in a while.

**Comment by b3yond** [comment]
doesn't work yet, not even text works anymore.

test case:

```
1. send text email to testfrei@ticketfrei.links-tech.org

1. send signed text email to testfrei@ticketfrei.links-tech.org

1. send html email reply to testfrei@ticketfrei.links-tech.org

1. send signed html email reply to testfrei@ticketfrei.links-tech.org

1. send html email to testfrei@ticketfrei.links-tech.org

1. send signed html email to testfrei@ticketfrei.links-tech.org

expected:

all are tweeted

actual:

all landed in /var/mail/tech, but none was tweeted.

```

**Comment by b3yond** [comment]
pgp signed mails don't get posted yet, but the other mails went through.

another test run would be nice, but I'm too fucking tired.

**Comment by b3yond** [comment]
pgp signed mails don't throw errors anymore. They are still not posted. Nasty, but I would not consider it a release blocker.

**Comment by d24phant** [comment]
Me neither ;) Not perfect, but shouldn't prevent from releasing!
