### ISSUE TITLE
[Crash] except other Telegram API error codes

### ISSUE THREAD

**Issue by b3yond** [b3yond/ticketfrei#42]
The bot crashed with this traceback:

```
Shutdown.
Traceback (most recent call last):
  File "backend.py", line 37, in <module>
    reports = bot.crawl(user)
  File "/srv/ticketfrei/active_bots/telegrambot.py", line 25, in crawl
    user.save_seen_tg(update.update_id)
AttributeError: 'int' object has no attribute 'update_id'
```

sometimes the Telegram API returns an error code as an integer. update is something like 404 in this case. Yet, we only except the error code 404, which Telegram also uses for bad auth. I thought they were too lazy to use different ones. But probably we just ran in another error code. a shame that it isn't included in the traceback.

@git-sid

**Comment by b3yond** [comment]
Here is a list of Telegram API return error codes: https://core.telegram.org/api/errors

we could think about all those error codes and implement them correctly, or just look if update is an integer and return an empy mentions list.

**Comment by b3yond** [comment]
This can not really be tested - we don't control the Telegram API. At least, when new error codes appear, they are logged now.
