### ISSUE TITLE
Rewrite twitter-bot in python3 with tweepy

### ISSUE THREAD

**Issue by b3yond** [b3yond/ticketfrei#7]
Tweepy is a twitter library for python3: http://tweepy.readthedocs.io/en/v3.5.0/getting_started.html#introduction

as the mastodon bot is already in python3, this enables more code consistency & modularity.

**Comment by b3yond** [comment]
so far done, but not committed:

* changed auth mechanism to tweepy
* changed shutdown handling to tweepy
* changed error handling to tweepy
* changed print statements to python3

yet to do:

* find a way to crawl mentions with tweepy
* retweet with tweepy
* post mastodon statuses with tweepy
* maybe other stuff I didn't find yet
* test

**Comment by b3yond** [comment]
the mastodon bot still has issues. Since it was also transfered from python2 -> python3, there is an error with pickle.dump:

```
Path of logfile: logs/2017-12-30 10:32:43.723493
Traceback (most recent call last):
  File "ticketfrei.py", line 30, in <module>
    statuses = mbot.retoot(statuses)
  File "/home/ticketfrei/ticketfrei/retootbot.py", line 105, in retoot
    pickle.dump(self.seen_toots, f)
TypeError: write() argument must be str, not bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ticketfrei.py", line 36, in <module>
    tbot.log(traceback.extract_tb(sys.exc_info()[2]))
  File "/home/ticketfrei/ticketfrei/retweetbot.py", line 96, in log
    line = "[" + time + "] " + message + "\n"
TypeError: Can't convert 'StackSummary' object to str implicitly
```

**Comment by b3yond** [comment]
okay, tom fixed it.
